name: clisitef_external_pinpad_example
description: Demonstrates how to use the clisitef plugin.
publish_to: "none"

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  clisitef_external_pinpad:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  